export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PHONE: 'INVALID_PHONE',
  RATE_LIMITED: 'RATE_LIMITED',
  BB_OFFLINE: 'BB_OFFLINE',
  BB_IMESSAGE_DISCONNECTED: 'BB_IMESSAGE_DISCONNECTED',
  SEND_FAILED: 'SEND_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',
  AUTH_FAILURE: 'AUTH_FAILURE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
